/**
 * This file was generated by AI.
 */

int startswith(const char *s, const char *prefix)
{
    if (!s || !prefix)               /* reject NULL pointers          */
        return 0;

    /* Walk both strings together until the prefix ends.      */
    while (*prefix != '\0') {
        if (*s == '\0' || *s != *prefix)   /* mismatch or s too short   */
            return 0;
        ++s; ++prefix;
    }
    return 1;                      /* all characters matched      */
}
