#!/usr/bin/env python3
"""Inline every local header/source into a single .c file for easy embedding.

Local includes (#include "...") are textually inlined (each header only
once, on first use). System includes (#include <...>) are stripped out of
the body and collected at the top, deduplicated.
"""
import os
import re
import sys

SRC_ROOT = os.path.join(os.path.dirname(__file__), "..", "src")
EXCLUDE = {"main.c"}

LOCAL_INCLUDE_RE = re.compile(r'^\s*#include\s*"([^"]+)"\s*$')
SYSTEM_INCLUDE_RE = re.compile(r'^\s*#include\s*<([^>]+)>\s*$')


def find_sources(root):
    out = []
    for dirpath, _, filenames in os.walk(root):
        for name in sorted(filenames):
            if name.endswith(".c") and name not in EXCLUDE:
                out.append(os.path.join(dirpath, name))
    return sorted(out)


def process(path, visited_headers, system_includes, body):
    curdir = os.path.dirname(path)
    with open(path) as f:
        for line in f:
            m = LOCAL_INCLUDE_RE.match(line)
            if m:
                resolved = os.path.normpath(os.path.join(curdir, m.group(1)))
                if not os.path.isfile(resolved):
                    # Not actually a local file (e.g. #include "stdbool.h") --
                    # treat like a system include instead.
                    system_includes.add(m.group(1))
                    continue
                if resolved in visited_headers:
                    continue
                visited_headers.add(resolved)
                body.append(f"/* --- inlined: {os.path.relpath(resolved, SRC_ROOT)} --- */\n")
                process(resolved, visited_headers, system_includes, body)
                continue
            m = SYSTEM_INCLUDE_RE.match(line)
            if m:
                system_includes.add(m.group(1))
                continue
            body.append(line)


def main():
    sources = find_sources(SRC_ROOT)
    visited_headers = set()
    system_includes = set()
    body = []
    for src in sources:
        body.append(f"/* ============ {os.path.relpath(src, SRC_ROOT)} ============ */\n")
        process(src, visited_headers, system_includes, body)

    out = sys.stdout
    out.write("/* Auto-generated amalgamated single-file build of rapids-vm-embedable.\n")
    out.write(" * Generated by scripts/amalgamate.py -- do not edit directly. */\n\n")
    for inc in sorted(system_includes):
        out.write(f"#include <{inc}>\n")
    out.write("\n")
    out.writelines(body)


if __name__ == "__main__":
    main()
